=== AsleepShaman/MII-Lab1/staff_project/xml/Organizations_and_personal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by MESMERiZE (MiZE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Staff">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Organization" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Person" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Tab_ID" type="xs:string"/>
										<xs:element name="Surname" type="xs:string"/>
										<xs:element name="Name" type="xs:string"/>
										<xs:element name="Patronymic" type="xs:string"/>
										<xs:element name="Subdivizion" type="xs:string"/>
										<xs:element name="Sex" type="xs:string"/>
										<xs:element name="Emp_date" type="xs:date"/>
									</xs:sequence>
									<xs:attribute name="UUID" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required" form="qualified"/>
						<xs:attribute name="UUID" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AsleepShaman/MII-Lab1/staff_project/bin/Staff.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 (http://www.altova.com)-->
<Staff xsi:noNamespaceSchemaLocation="Organizations_and_personal.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

        <Organization Name="Augsburger" UUID="{1134c2c7-6bd2-4055-a79d-b9e79bd5cdae}">
            <Subdivizion Name="Отдел-4" UUID="{26c071f6-0c40-4a44-84ef-b6407535b31a}">
                <Person UUID="{e42185cb-2bad-4127-9e49-2977fff4d7a3}">
			<Tab_ID>111111</Tab_ID>
			<Surname>Иванов</Surname>
			<Name>Иван</Name>
			<Patronymic>Иванович</Patronymic>
			<Sex>м</Sex>
			<Emp_date>2012-02-03</Emp_date>
		</Person>
		
                <Person UUID="{3a68c74e-c44d-4f40-bc85-9d3eeea76d91}">
			<Tab_ID>222222</Tab_ID>
			<Surname>Петрова</Surname>
			<Name>Анна</Name>
			<Patronymic>Сергеевна</Patronymic>
			<Sex>ж</Sex>
			<Emp_date>2017-03-26</Emp_date>
		</Person>
            </Subdivizion>

            <Subdivizion Name="Отдел-5" UUID="{03cc9910-f1ed-4ec2-926f-a52a536a1a11}">
                <Person UUID="{dbb78052-801e-45a5-806c-dbdcaec51ee7}">
			<Tab_ID>333333</Tab_ID>
			<Surname>Сидоров</Surname>
			<Name>Андрей</Name>
			<Patronymic>Андреевич</Patronymic>
			<Sex>м</Sex>
			<Emp_date>2006-09-13</Emp_date>
		</Person>
            </Subdivizion>

            <Subdivizion Name="Отдел-6" UUID="{80e88312-f6ae-456a-a63a-b506a82bbdb7}">
                <Person UUID="{97e34258-93e5-4fba-bacc-85b4b7d8efed}">
			<Tab_ID>444444</Tab_ID>
			<Surname>Сергеев</Surname>
			<Name>Михаил</Name>
			<Patronymic>Викторович</Patronymic>
                        <Sex>м</Sex>
			<Emp_date>2010-08-30</Emp_date>
		</Person>
            </Subdivizion>
	</Organization>
	
        <Organization Name="Mile a minute" UUID="{0449eac9-216e-40fc-8d30-1a31f8f00aee}">
            <Subdivizion Name="Отдел-1" UUID="{707a677a-2210-4653-934c-e0d264e8a8f1}">
                <Person UUID="{744ff62e-8947-4d38-bbca-2766959f924d}">
			<Tab_ID>555555</Tab_ID>
			<Surname>Позин</Surname>
			<Name>Станислав</Name>
			<Patronymic>Петрович</Patronymic>
			<Sex>м</Sex>
			<Emp_date>2020-10-24</Emp_date>
		</Person>

                <Person UUID="{73d6fdd8-7320-4709-8670-bcd82ad6cb39}">
                        <Tab_ID>777777</Tab_ID>
                        <Surname>Разумовская</Surname>
                        <Name>Катерина</Name>
                        <Patronymic>Андреевна</Patronymic>
                        <Sex>ж</Sex>
                        <Emp_date>2004-07-13</Emp_date>
                </Person>
            </Subdivizion>

            <Subdivizion Name="Отдел-2" UUID="{3a98c821-b656-4b97-bee0-bee91822b6af}">
                <Person UUID="{3c2c6fe8-3792-482e-8a2b-14ffcf91dbd8}">
			<Tab_ID>888888</Tab_ID>
			<Surname>Петров</Surname>
			<Name>Олег</Name>
			<Patronymic>Иванович</Patronymic>
			<Sex>м</Sex>
			<Emp_date>1999-04-20</Emp_date>
		</Person>
		
                <Person UUID="{6b951ee3-cf28-45ad-9616-2c66aed9209d}">
			<Tab_ID>999999</Tab_ID>
			<Surname>Иванова</Surname>
			<Name>Ирина</Name>
                        <Patronymic>Петровна</Patronymic>
			<Sex>ж</Sex>
			<Emp_date>2014-09-16</Emp_date>
		</Person>
            </Subdivizion>

            <Subdivizion Name="Отдел-3" UUID="{5d271340-0a11-4846-a92c-0f34be191215}">
                <Person UUID="{dddc74f1-e4e5-43f7-a319-8ffbc8c49c1c}">
                        <Tab_ID>666666</Tab_ID>
                        <Surname>Волкова</Surname>
                        <Name>Ирина</Name>
                        <Patronymic>Алексеевна</Patronymic>
                        <Sex>ж</Sex>
                        <Emp_date>2019-12-14</Emp_date>
                </Person>
		
                <Person UUID="{f5f9c285-8461-495d-8a60-4901445fd5c5}">
			<Tab_ID>121212</Tab_ID>
			<Surname>Сидорова</Surname>
			<Name>Мария</Name>
			<Patronymic>Александровна</Patronymic>
			<Sex>ж</Sex>
			<Emp_date>1997-08-13</Emp_date>
		</Person>
            </Subdivizion>
	</Organization>	
</Staff>
